# Generated by Django 4.1.1 on 2022-10-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsystem', '0006_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default=True, upload_to='images/profile_images'),
        ),
    ]
