# Generated by Django 4.1.1 on 2022-10-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsystem', '0007_user_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_photo',
            new_name='image',
        ),
    ]
