# Generated by Django 4.1.1 on 2022-11-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsystem', '0011_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=True, max_length=60, unique=True, verbose_name='email address'),
        ),
    ]
