# Generated by Django 4.1.1 on 2022-12-21 06:45

from django.db import migrations, models
import loginsystem.models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsystem', '0021_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='codingwithmelika/default_image.png', upload_to=loginsystem.models.user_directory_path),
        ),
    ]
