# Generated by Django 4.1.1 on 2023-01-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('سفر', 'travel'), ('رویدادها', 'event')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='cat', to='post_details.category'),
        ),
    ]
