# Generated by Django 4.1.1 on 2023-02-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_details', '0004_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
    ]
