# Generated by Django 4.1.1 on 2023-02-22 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_details', '0007_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='post',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='post_details.post'),
        ),
    ]
