# Generated by Django 4.1.1 on 2023-02-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_details', '0008_teacher_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher',
            new_name='author',
        ),
    ]
