# Generated by Django 4.1.1 on 2023-02-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_details', '0009_rename_teacher_teacher_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
    ]
