# Generated by Django 4.1.1 on 2023-02-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_details', '0010_remove_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='codingwithmelika/default_video_image.jpg', upload_to='images/'),
        ),
    ]
