# Generated by Django 4.1.1 on 2023-02-27 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_details', '0011_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='post',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='author',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
