# Generated by Django 4.1.1 on 2023-02-27 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_details', '0013_alter_post_author_alter_teacher_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='author',
            field=models.ForeignKey(default=True, limit_choices_to={'is_admin': True}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
